spring.application.name=Erum-Makeover

server.port=${PORT:8080}
# server.port =8080
aws.access-key=${AWS_ACCESS_KEY_ID}
spring.mongodb.uri=${MONGO_URI}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_BUCKET_NAME}

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}

spring.cache.type=redis
spring.redis.host=${REDISHOST}
spring.redis.port=${REDISPORT}
spring.redis.password=${REDISPASSWORD}
spring.redis.ssl.enabled=true
spring.redis.timeout=60000